In [21]:
import numpy as np

In [130]:
matrix = np.array([
    [0, 1, 5, 1, 6, 8],
    [0, 0, 4 ,5, 5, 1],
    [0, 0, 0, 7, 1, 9],
    [0, 0, 0, 0, 8, 1],
    [0, 0, 0, 0, 0, 6],
    [0, 0, 0, 0, 0, 0],
])

In [131]:
mat = matrix.transpose() + matrix

In [132]:
mat

array([[0, 1, 5, 1, 6, 8],
       [1, 0, 4, 5, 5, 1],
       [5, 4, 0, 7, 1, 9],
       [1, 5, 7, 0, 8, 1],
       [6, 5, 1, 8, 0, 6],
       [8, 1, 9, 1, 6, 0]])

In [177]:
idx = [0, 2, 4, 0]

In [178]:
mat[idx]

array([[0, 1, 5, 1, 6, 8],
       [5, 4, 0, 7, 1, 9],
       [6, 5, 1, 8, 0, 6],
       [0, 1, 5, 1, 6, 8]])

In [179]:
status = [False, True, False, True, False, True]
st2idx = np.where(status)
print(st2idx)

(array([1, 3, 5]),)


In [180]:
def count_snp_diffs(x, y): 
    return np.sum([x, y], axis=0)

In [181]:
import itertools

In [223]:
combinations = np.array(list(itertools.combinations(range(mat.shape[1]),2)))

combinations = np.array(list(map(np.array, zip(idx[:-1], idx[1:]))))

print(combinations)

[[0 2]
 [2 4]
 [4 0]]


In [224]:
dist = count_snp_diffs(mat[:,combinations[:,0]], mat[:,combinations[:,1]])
print(dist)

[[ 5 11  6]
 [ 5  9  6]
 [ 5  1  6]
 [ 8 15  9]
 [ 7  1  6]
 [17 15 14]]


In [225]:
dist = np.sum([mat[:,combinations[:,0]], mat[:,combinations[:,1]]], axis=0)

In [226]:
np.unravel_index(np.argmin(dist[st2idx], axis=None), dist.shape)

(0, 0)

In [227]:
dist[st2idx]

array([[ 5,  9,  6],
       [ 8, 15,  9],
       [17, 15, 14]])

In [228]:
st2idx

(array([1, 3, 5]),)

In [188]:
a = dist[st2idx]
print(f'a:\n{a}')
b = mat[st2idx, idx[:-1]]
print(f'b:\n{b}')
dist[st2idx] - mat[st2idx, idx[:-1]]

a:
[[ 5  9  6]
 [ 8 15  9]
 [17 15 14]]
b:
[[1 7 6]]


array([[ 4,  2,  0],
       [ 7,  8,  3],
       [16,  8,  8]])

In [189]:
mat

array([[0, 1, 5, 1, 6, 8],
       [1, 0, 4, 5, 5, 1],
       [5, 4, 0, 7, 1, 9],
       [1, 5, 7, 0, 8, 1],
       [6, 5, 1, 8, 0, 6],
       [8, 1, 9, 1, 6, 0]])

In [195]:
combinations

array([[0, 2],
       [2, 4],
       [4, 0]])

In [214]:
np.tile(mat[combinations[:,0], combinations[:,1]], (3, 1))

array([[5, 1, 6],
       [5, 1, 6],
       [5, 1, 6]])

In [192]:
combinations[:,1]

array([2, 4, 0])

In [216]:
combinations.shape

(3, 2)

In [230]:
dist = np.sum([mat[:,combinations[:,0]], mat[:,combinations[:,1]]], axis=0)
dist

array([[ 5, 11,  6],
       [ 5,  9,  6],
       [ 5,  1,  6],
       [ 8, 15,  9],
       [ 7,  1,  6],
       [17, 15, 14]])

In [235]:
mat

array([[0, 1, 5, 1, 6, 8],
       [1, 0, 4, 5, 5, 1],
       [5, 4, 0, 7, 1, 9],
       [1, 5, 7, 0, 8, 1],
       [6, 5, 1, 8, 0, 6],
       [8, 1, 9, 1, 6, 0]])

In [238]:
st2idx = [0, 1, 3, 5]
edges = np.array([[3, 1, 5], [5, 3, 0]])
position = 1
edges_zipped = zip()

In [244]:
np.array([mat[edges[:, 0], edges[:, 1]], mat[edges[:, 0], edges[:, 2]]])

array([[5, 1],
       [1, 8]])